import { Header } from "@/components/header"
import Head from "next/head";
import { ReactNode } from "react"
import styles from "./styles.module.css"

//Defino as propriedades que vai ter no meu layout
interface IProps {
    title: string;
    subtitle: string;
    children: ReactNode;
}

export function DefaultLayout({ title, subtitle, children }: IProps) {
    return (
        <>
            <Head>  //Componente proprio do next para criar um Head
                <title>{`Pegasus - ${title}`}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.content}>
                <Header />  //Componente proprio do next
                <div className={styles.body}>       //Abaixo passo os parametros dentro das tags
                    <h1>{title}</h1>
                    <hr />
                    <p>{subtitle}</p>
                    {children}
                </div>
            </div>
        </>
    )
}