import { Header } from "@/components/header"
import Head from "next/head";
import { ReactNode } from "react"
import styles from "./styles.module.css"
import { Button } from "react-bootstrap";
import { FaArrowLeft } from "react-icons/fa6";
import { useRouter } from "next/router";

//Defino as propriedades que vai ter no meu layout
interface IProps {
    title: string;
    subtitle: string;
    children: ReactNode;
    hideHeader?: boolean;
}

export function DefaultLayout({ title, subtitle, hideHeader, children }: IProps) {
    const { back } = useRouter()    //Voltar a pagina dentro do meu componentes react
    return (
        <>
            <Head>
                <title>{`Pegasus - ${title}`}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.content}>
                {
                    !hideHeader && <Header />
                }

                <div className={styles.body}>
                    <h1><Button onClick={back}><FaArrowLeft /></Button>{' '}{title}</h1>
                    <hr />
                    <p>{subtitle}</p>
                    {children}
                </div>
            </div>
        </>
    )
}